config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get :login, to: 'oauth#auth'
  get :logout, to: 'oauth#logout'

  namespace :oauth do
    get :callback
  end

  resources :tournaments do
    resources :players, only: [:index, :create, :update, :destroy] do
      get :standings, on: :collection
      get :meeting, on: :collection
      patch :drop, on: :member
      patch :reinstate, on: :member
    end
    resources :rounds, only: [:index, :show, :create, :edit, :update, :destroy] do
      resources :pairings, only: [:index, :create, :destroy] do
        post :report, on: :member
        get :match_slips, on: :collection
      end
      patch :repair, on: :member
      patch :complete, on: :member
    end
    resources :stages, only: [:create, :destroy]
    post :upload_to_abr, on: :member
    get :save_json, on: :member
    post :cut, on: :member
    get :qr, on: :member
    get :import_from_tome, on: :member
    post :apply_import_from_tome, on: :member
    get :import_from_csv, on: :member
    post :apply_import_from_csv, on: :member
    get :shortlink, on: :collection
    get :not_found, on: :collection
    get :my, on: :collection
  end
  resources :identities, only: [:index]

  get '/error', to: 'errors#show'

  get '/help', to: 'home#help'

  get ':slug', to: 'tournaments#shortlink'

  match '*path', to: redirect('/error'), via: :all
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :stage
  has_one :tournament, through: :stage
  has_many :pairings, -> { order(:table_number) }, dependent: :destroy

  default_scope { order(number: :asc) }
  scope :complete, -> { where(completed: true) }

  after_update_commit :cache_standings!, if: Proc.new { saved_change_to_completed? && completed? }
  delegate :cache_standings!, to: :stage

  def pair!
    Pairer.new(self).pair!
  end

  def unpaired_players
    @unpaired_players ||= tournament.players - pairings.map(&:players).flatten
  end

  def repair!
    pairings.destroy_all
    update(completed: false)
    pair!
  end

  def collated_pairings
    return pairings if pairings.count < 5

    pairings
      .in_groups_of((pairings.count/4.0).ceil)
      .transpose
      .flatten
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_tournament
  before_action :set_round, only: [:show, :edit, :update, :destroy, :repair, :complete]

  def index
    authorize @tournament, :show?
    @players = @tournament.players.index_by(&:id).merge({ nil => NilPlayer.new })
  end

  def show
    authorize @tournament, :update?
    @players = @tournament.players.index_by(&:id).merge({ nil => NilPlayer.new })
  end

  def create
    authorize @tournament, :update?

    @tournament.pair_new_round!

    redirect_to tournament_rounds_path(@tournament)
  end

  def edit
    authorize @tournament, :update?
  end

  def update
    authorize @tournament, :update?

    @round.update(round_params)

    redirect_to tournament_round_path(@tournament, @round)
  end

  def destroy
    authorize @tournament, :update?

    @round.destroy!

    redirect_to tournament_rounds_path(@tournament)
  end

  def repair
    authorize @tournament, :update?

    @round.repair!

    redirect_to tournament_round_path(@tournament, @round)
  end

  def complete
    authorize @tournament, :update?

    @round.update!(completed: params[:completed])

    redirect_to tournament_rounds_path(@tournament)
  end

  private

  def set_round
    @round = Round.find(params[:id])
  end

  def round_params
    params.require(:round).permit(:weight)
  end
end

app/views/rounds/_pairings.html.slim
- single_sided = round.stage.single_sided?
- round.pairings.each do |pairing|
  .row.m-1.round_pairing class="table_#{pairing.table_number} #{'reported' if pairing.reported? && current_user == @tournament.user}"
    .col-sm-2 Table #{pairing.table_number}
    .col-sm.left_player_name
      = @players[pairing.player1_id].name
      =< render 'player_side', pairing: pairing, player: @players[pairing.player1_id], single_sided: single_sided
      - if @players[pairing.player1_id].id
        .ids
          = render @players[pairing.player1_id].corp_identity_object
          = render @players[pairing.player1_id].runner_identity_object
    - if policy(round.tournament).edit?
      .col-sm-5.centre_score
        .preset_score
          - presets(pairing).each do |data|
            => preset_score_button pairing, data
          = link_to '...', '#', class: 'btn btn-primary toggle_custom_score'
        .custom_score
          = simple_form_for pairing, url: report_tournament_round_pairing_path(round.tournament, round, pairing), method: :post, html: { class: 'form-inline' } do |f|
            .mx-auto
              = f.hidden_field :score1_runner, value: 0
              = f.hidden_field :score1_corp, value: 0
              = f.hidden_field :score2_runner, value: 0
              = f.hidden_field :score2_corp, value: 0
              = f.text_field :score1, style: 'width: 2.5em;', class: 'form-control'
              = button_tag type: :submit, class: 'btn btn-primary mx-2' do
                => fa_icon 'flag-checkered'
                | Save
              = f.text_field :score2, style: 'width: 2.5em;', class: 'form-control'
              =< link_to '...', '#', class: 'btn btn-primary toggle_custom_score'
    - else
      .col-sm-2.centre_score
        = readable_score(pairing)
    .col-sm.right_player_name
      = @players[pairing.player2_id].name
      =< render 'player_side', pairing: pairing, player: @players[pairing.player2_id], single_sided: single_sided
      - if @players[pairing.player2_id].id
        .ids
          = render @players[pairing.player2_id].corp_identity_object
          = render @players[pairing.player2_id].runner_identity_object
    - if policy(round.tournament).update?
      .col-sm-1
        = link_to tournament_round_pairing_path(round.tournament, round, pairing), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure? This cannot be reversed.' } do
          => fa_icon 'trash'

app/views/rounds/_player_side.html.slim
- if single_sided
  - if policy(pairing.tournament).update?
    = set_side_button(player, :corp, pairing)
    = set_side_button(player, :runner, pairing)
  - else
    = side_label_for(pairing, player)

app/views/rounds/_round.html.slim
- if round.stage.players.count < 100 || round == @tournament.stages.last.rounds.last
  .card
    .card-header role="tab"
      .row
        .col-sm-9
          a data-toggle="collapse" href="#round#{round.id}"
            h5.mb-0 Round #{round.number}
        .col-sm-3
          | #{round.pairings.reported.count} / #{round.pairings.count} pairings reported

    .collapse id="round#{round.id}" class=("show" if round == @tournament.stages.last.rounds.last)
      .col-12.my-3
        - if policy(round.tournament).edit?
          = link_to tournament_round_path(round.tournament, round), class: 'btn btn-warning' do
            => fa_icon 'pencil'
            | Edit
          - unless round.completed?
            =< link_to complete_tournament_round_path(round.tournament, round, completed: true), method: :patch, class: 'btn btn-warning' do
              => fa_icon 'check'
              | Complete
          =< link_to match_slips_tournament_round_pairings_path(round.tournament, round), class: 'btn btn-primary' do
            => fa_icon 'flag-checkered'
            | Match slips
        =< link_to tournament_round_pairings_path(round.tournament, round), class: 'btn btn-primary' do
          => fa_icon 'list-ul'
          | Pairings by name
        = render 'pairings', round: round

app/views/rounds/edit.html.slim
.col-12
  h2= "Round #{@round.number}: Advanced Settings"
  => link_to tournament_round_path(@tournament, @round), class: 'btn btn-primary' do
    => fa_icon 'arrow-left'
    | Back to round
.col-12.mt-3
  .row
    .col-4
      = simple_form_for @round, url: tournament_round_path(@tournament, @round) do |f|
        .form-group
          = f.input :weight, input_html: { class: 'form-control' }, label: 'SOS Weighting'
        .form-group
          = button_tag type: :submit, class: 'btn btn-primary' do |f|
            => fa_icon 'floppy-o'
            | Save

app/views/rounds/index.html.slim
.col-12
  - if @tournament.stages.empty?
    - if policy(@tournament).update?
      = link_to tournament_stages_path(@tournament), method: :post, class: 'btn btn-success' do
        => fa_icon 'plus'
        | Add Swiss stage
  - else
    - if policy(@tournament).update?
      p
        #toggle_reported.btn.btn-primary
          => fa_icon 'eye-slash'
          | Show/hide reported pairings
      .reported_hidden_message.alert.alert-info Reported scores are currently hidden on this page. This will not affect other users viewing this page.
    - if @tournament.rounds.empty?
      p= link_to meeting_tournament_players_path(@tournament), class: 'btn btn-primary' do
        => fa_icon 'list-ul'
        | Player meeting
    - else
      p
        #toggle_identities.btn.btn-primary
          => fa_icon 'eye-slash'
          | Show/hide identities

    = render @tournament.stages

    - if policy(@tournament).update?
      - if @tournament.rounds.all?(&:completed?)
        p=> link_to tournament_rounds_path(@tournament), method: :post, class: 'btn btn-success' do
          => fa_icon 'plus'
          | Pair new round!
      - else
        p
          .btn.btn-secondary.mr-3.disabled
            => fa_icon 'plus'
            | Pair new round!
          | All rounds must be flagged complete before you can add a new round
      - unless @tournament.stages.last.double_elim?
        p
          => link_to cut_tournament_path(@tournament, number: 4), method: :post, class: 'btn btn-success' do
            => fa_icon 'scissors'
            | Cut to Top 4
          = link_to cut_tournament_path(@tournament, number: 8), method: :post, class: 'btn btn-success' do
            => fa_icon 'scissors'
            | Cut to Top 8

app/views/rounds/show.html.slim
.col-12
  h2= "Round #{@round.number}"
  p
    => link_to tournament_rounds_path(@round.tournament), class: 'btn btn-primary' do
      => fa_icon 'arrow-left'
      | Back to pairings
    - if policy(@round.tournament).update?
      => link_to repair_tournament_round_path(@round.tournament, @round), method: :patch, class: 'btn btn-warning', data: { confirm: 'Are you sure? This cannot be reversed.' } do
        => fa_icon 'refresh'
        | Re-pair
      - if @round.completed?
        => link_to complete_tournament_round_path(@round.tournament, @round, completed: false), method: :patch, class: 'btn btn-warning' do
          => fa_icon 'backward'
          | Uncomplete
      - else
        => link_to complete_tournament_round_path(@round.tournament, @round, completed: true), method: :patch, class: 'btn btn-warning' do
          => fa_icon 'check'
          | Complete
      => link_to edit_tournament_round_path(@round.tournament, @round), class: 'btn btn-warning' do
        => fa_icon 'wrench'
        | Advanced
      = link_to tournament_round_path(@round.tournament, @round), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure? This cannot be reversed.' } do
        => fa_icon 'trash'
        | Delete round
  = render 'pairings', round: @round

h3.mt-2.col-12 Unpaired players
- if @round.unpaired_players.any?
  - @round.unpaired_players.each do |player|
    = render player
  h3.mt-2.col-12 Create pairing
  = simple_form_for @round.pairings.build, url: tournament_round_pairings_path(@round.tournament, @round), html: { class: 'form-inline col-12' } do |f|
    = f.text_field :table_number, placeholder: 'Table number', class: 'form-control'
    = pairing_player_select(f, :player1_id, @round)
    | vs
    = pairing_player_select(f, :player2_id, @round)
    - unless @round.tournament.swiss?
      = f.select :side, side_options, include_blank: true
    = button_tag type: :submit, class: 'btn btn-success' do
      => fa_icon 'plus'
      | Create
- else
  ' None