config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get :login, to: 'oauth#auth'
  get :logout, to: 'oauth#logout'

  namespace :oauth do
    get :callback
  end

  resources :tournaments do
    resources :players, only: [:index, :create, :update, :destroy] do
      get :standings, on: :collection
      get :meeting, on: :collection
      patch :drop, on: :member
      patch :reinstate, on: :member
    end
    resources :rounds, only: [:index, :show, :create, :edit, :update, :destroy] do
      resources :pairings, only: [:index, :create, :destroy] do
        post :report, on: :member
        get :match_slips, on: :collection
      end
      patch :repair, on: :member
      patch :complete, on: :member
    end
    resources :stages, only: [:create, :destroy]
    post :upload_to_abr, on: :member
    get :save_json, on: :member
    post :cut, on: :member
    get :qr, on: :member
    get :import_from_tome, on: :member
    post :apply_import_from_tome, on: :member
    get :import_from_csv, on: :member
    post :apply_import_from_csv, on: :member
    get :shortlink, on: :collection
    get :not_found, on: :collection
    get :my, on: :collection
  end
  resources :identities, only: [:index]

  get '/error', to: 'errors#show'

  get '/help', to: 'home#help'

  get ':slug', to: 'tournaments#shortlink'

  match '*path', to: redirect('/error'), via: :all
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :players, -> { order(:id) }, dependent: :destroy
  belongs_to :user
  has_many :stages, -> { order(:number) }, dependent: :destroy
  has_many :rounds, through: :stages

  enum stage: {
    swiss: 0,
    double_elim: 1
  }

  delegate :pair_new_round!, to: :current_stage

  validates :name, :slug, presence: true
  validates :slug, uniqueness: true

  before_validation :generate_slug, on: :create, unless: :slug
  before_create :default_date, unless: :date
  after_create :create_stage

  def cut_to!(format, number)
    previous_stage = current_stage
    stages.create!(
      format: format,
      number: previous_stage.number + 1
    ).tap do |stage|
      previous_stage.top(number).each_with_index do |player, i|
        stage.registrations.create!(
          player: player,
          seed: i + 1
        )
      end
    end
  end

  def corp_counts
    players.group_by(&:corp_identity).map do |id, players|
      [
        Identity.find_or_initialize_by(name: id),
        players.count
      ]
    end.sort_by(&:last).reverse
  end

  def runner_counts
    players.group_by(&:runner_identity).map do |id, players|
      [
        Identity.find_or_initialize_by(name: id),
        players.count
      ]
    end.sort_by(&:last).reverse
  end

  def generate_slug
    self.slug = rand(36**4).to_s(36).upcase
    generate_slug if Tournament.exists?(slug: slug)
  end

  def qr
    @qr ||= RQRCode::QRCode.new(
      "http://cobr.ai/#{slug.downcase}",
      size: 4,
      level: :h
    ) if slug
  end

  def current_stage
    stages.last
  end

  private

  def default_date
    self.date = Date.today
  end

  def create_stage
    stages.create(
      number: 1,
      format: :swiss
    )
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [
      :show, :edit, :update, :destroy,
      :upload_to_abr, :save_json, :cut, :qr,
      :import_from_tome, :apply_import_from_tome,
      :import_from_csv, :apply_import_from_csv
    ]

  def index
    authorize Tournament

    @tournaments = Tournament.where(private: false)
      .order(date: :desc)
      .limit(20)
  end

  def my
    authorize Tournament

    @tournaments = current_user.tournaments.order(date: :desc)
  end

  def show
    authorize @tournament

    respond_to do |format|
      format.html do
        @players = @tournament.players.active.sort_by { |p| p.name || '' }
        @dropped = @tournament.players.dropped.sort_by { |p| p.name || '' }
      end
      format.json do
        headers['Access-Control-Allow-Origin'] = '*'
        render json: NrtmJson.new(@tournament).data
      end
    end
  end

  def new
    authorize Tournament

    @new_tournament = current_user.tournaments.new
    @new_tournament.date = Date.today
  end

  def create
    authorize Tournament

    @new_tournament = current_user.tournaments.new(tournament_params)

    if @new_tournament.save
      redirect_to tournament_path(@new_tournament)
    else
      render :new
    end
  end

  def edit
    authorize @tournament
  end

  def update
    authorize @tournament

    @tournament.update(tournament_params)

    redirect_to edit_tournament_path(@tournament)
  end

  def destroy
    authorize @tournament

    @tournament.destroy!

    redirect_to tournaments_path
  end

  def upload_to_abr
    authorize @tournament

    response = AbrUpload.upload!(@tournament)

    if(response[:code])
      @tournament.update(abr_code: response[:code])
    end

    redirect_to edit_tournament_path(@tournament)
  end

  def save_json
    authorize @tournament

    data = NrtmJson.new(@tournament).data

    send_data data.to_json,
      type: :json,
      disposition: :attachment,
      filename: "#{@tournament.name.underscore}.json"
  end

  def cut
    authorize @tournament

    number = params[:number].to_i
    return redirect_to standings_tournament_players_path(@tournament) unless [4,8,16].include? number

    @tournament.cut_to!(:double_elim, number)

    redirect_to tournament_rounds_path(@tournament)
  end

  def shortlink
    tournament = Tournament.find_by!(slug: params[:slug].upcase)

    authorize tournament, :show?

    redirect_to tournament_path(tournament)
  rescue ActiveRecord::RecordNotFound
    skip_authorization

    redirect_to not_found_tournaments_path(code: params[:slug])
  end

  def not_found
    skip_authorization

    @code = params[:code]
  end

  def qr
    authorize @tournament, :edit?
  end

  def import_from_tome
    authorize @tournament, :edit?
  end

  def apply_import_from_tome
    authorize @tournament, :edit?

    Import::Tome.new(tome_import_params[:tome_import]).apply(@tournament)

    redirect_to tournament_players_path(@tournament)
  end

  def import_from_csv
    authorize @tournament, :edit?
  end

  def apply_import_from_csv
    authorize @tournament, :edit?

    Import::CSV_Import.new(csv_import_params[:csv_import]).apply(@tournament)

    redirect_to tournament_players_path(@tournament)
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def tournament_params
    params.require(:tournament).permit(:name, :date, :private, :stream_url, :manual_seed)
  end

  def tome_import_params
    params.require(:tome_import).permit(:tome_import)
  end

  def csv_import_params
    params.require(:csv_import).permit(:csv_import)
  end
end

app/helpers/tournament_helper.rb
module TournamentHelper
  def short_date(tournament)
    return unless tournament.date

    tournament.date.strftime('%-d %b %Y')
  end
end

app/views/tournaments/_form.html.slim
.form-group
  = f.input :name, input_html: { class: 'form-control' }, label: 'Tournament name'
.form-group
  = f.input :date, html5: true, input_html: { class: 'form-control' }
.form-group
  = f.input :stream_url, input_html: { class: 'form-control' }, label: 'Stream URL'
.form-group
  = f.input :private, as: :boolean, inline_label: 'Private: Only I will be able to view this tournament'
.form-group
  = f.input :manual_seed, as: :boolean, inline_label: 'Use manual seeding for tiebreakers: Players can be assigned a "seed" value that will be used before all other tiebreakers (in ascending order; i.e. Seed 1 wins all ties)'

app/views/tournaments/_registering.html.slim
p This tournament is: REGISTERING
p Add players to your tournament!
= simple_form_for :player, url: tournament_players_path(@tournament) do |f|
  = f.input :name
  = f.submit 'Register Player'

app/views/tournaments/_tournament.html.slim
= link_to tournament_path(tournament) do
  .tournament.card.m-3
    .card-body
      h4.card-title= tournament.name
      h6.card-subtitle.mb-2.text-muted
        => short_date(tournament)
        ' -
        => pluralize(tournament.players.active.count, 'player')
        ' -
        => tournament.user.try(:nrdb_username)
        - if tournament.stream_url.present?
          ' -
          => fa_icon 'video-camera'
      - if policy(tournament).destroy?
        .delete_action= link_to tournament_path(tournament), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure? This cannot be reversed.' } do
          => fa_icon 'trash-o'
          | Delete

app/views/tournaments/edit.html.slim
  .col-md-6
    = simple_form_for @tournament do |f|
      = render 'form', f: f
      .form-group
        = button_tag type: :submit, class: 'btn btn-primary' do |f|
          => fa_icon 'floppy-o'
          | Save

  .col-md-3
  .col-md-3
    p=> link_to upload_to_abr_tournament_path(@tournament), class: 'btn btn-success', method: :post do |f|
      => fa_icon 'arrow-circle-up'
      | Upload to Always Be Running
    - if @tournament.abr_code
      | Uploaded to ABR with code #{@tournament.abr_code}
    p= link_to save_json_tournament_path(@tournament), class: 'btn btn-success', target: '_blank' do |f|
      => fa_icon 'arrow-circle-down'
      | Download as JSON
    p= button_to cut_tournament_path(@tournament, number: 4), method: :post, class: 'btn btn-success' do
      => fa_icon 'scissors'
      | Cut to Top 4
    p= button_to cut_tournament_path(@tournament, number: 8), method: :post, class: 'btn btn-success' do
      => fa_icon 'scissors'
      | Cut to Top 8
    p= button_to cut_tournament_path(@tournament, number: 16), method: :post, class: 'btn btn-success' do
      => fa_icon 'scissors'
      | Cut to Top 16
    p= link_to import_from_tome_tournament_path(@tournament), class: 'btn btn-warning' do |f|
      => fa_icon 'book'
      | Import from TOME
    p= link_to import_from_csv_tournament_path(@tournament), class: 'btn btn-warning' do
      => fa_icon 'book'
      | Import from CSV

app/views/tournaments/import_from_csv.html.slim
.col-md-12
  p This function takes a csv file with three columns: Player name, Corp ID, Runner ID

  .alert.alert-danger
    => fa_icon 'flask'
    | This feature is very experimental. All existing tournament data will be DELETED as part of this import process.

  = simple_form_for :csv_import, url: apply_import_from_csv_tournament_path(@tournament) do |f|
    .form-group
      = f.input :csv_import, label: 'CSV file', as: :file
    .form-group
      = button_tag type: :submit, class: 'btn btn-primary', data: { confirm: 'This action will DESTROY all existing data and CANNOT be reversed! Are you sure?' } do |f|
        => fa_icon 'download'
        | Import

app/views/tournaments/import_from_tome.html.slim
.col-md-12
  p Paste in the data from TOME's export feature to recreate your event in Cobra.

  .alert.alert-danger
    => fa_icon 'flask'
    | This feature is very experimental. All existing tournament data will be DELETED as part of this import process.

  = simple_form_for :tome_import, url: apply_import_from_tome_tournament_path(@tournament) do |f|
    .form-group
      = f.input :tome_import, input_html: { class: 'form-control' }, label: 'TOME data', as: :text
    .form-group
      = button_tag type: :submit, class: 'btn btn-primary', data: { confirm: 'This action will DESTROY all existing data and CANNOT be reversed! Are you sure?' } do |f|
        => fa_icon 'download'
        | Import

app/views/tournaments/index.html.slim
.col-12
  = render @tournaments

app/views/tournaments/my.html.slim
.col-12
  h4 My tournaments
  = render @tournaments

app/views/tournaments/new.html.slim
.col-12
  h1 Create a tournament
  = simple_form_for @new_tournament do |f|
    = render 'form', f: f
    .form-group
      = button_tag type: :submit, class: 'btn btn-primary' do |f|
        => fa_icon 'plus'
        | Create

app/views/tournaments/not_found.html.slim
.col-12
  .massive.text-center
    - if @code.upcase == 'SNEK'
      | 🐍
    - elsif @code.upcase == 'DOGE'
      = image_tag 'doge.jpg'
    - else
      = ['😢', '🤔', '🙃', '😣', '😱'].sample
.col-12.mb-4
  .text-center Couldn't find that tournament!

.col-12
  = simple_form_for :shortcode, url: shortlink_tournaments_path, method: :get, html: { class: 'form-inline justify-content-center' } do |f|
    label.mx-2 Try again?
    => f.text_field :slug, class: 'form-control mr-2', placeholder: 'SHRT', name: :slug, value: @code.upcase
    = button_tag type: :submit, class: 'btn btn-primary mr-2' do
      => fa_icon 'arrow-right'
      | Go to tournament

app/views/tournaments/qr.html.slim
.col-12.text-center
  h1.mb-5 cobr.ai/#{@tournament.slug}
  p= raw @tournament.qr.as_svg(offset: 0, color: '000',
                  shape_rendering: 'crispEdges',
                  module_size: 25)

app/views/tournaments/show.html.slim
.col-12
  - if @tournament.slug
    p
      ' Tournament shortcode:
      b #{@tournament.slug}
    p
      ' URL:
      = link_to "cobr.ai/#{@tournament.slug.downcase}", "http://cobr.ai/#{@tournament.slug}"
  p Organiser: #{@tournament.user.nrdb_username}
  p
    => pluralize(@players.count, 'active player')
    = "(#{@dropped.count} dropped)"

  - if policy(@tournament).edit?
    p
      = link_to qr_tournament_path(@tournament), class: 'btn btn-primary' do
        => fa_icon 'qrcode'
        | Printable QR code

- if @tournament.rounds.any? || policy(@tournament).edit?
  .col-12.mt-3.row
    .col-md-6
      table.table
        thead
          tr
            th Corp
            th Players
        tbody
          - @tournament.corp_counts.each do |id, count|
            tr
              td= render id
              td= count
    .col-md-6
      table.table
        thead
          tr
            th Runner
            th Players
        tbody
          - @tournament.runner_counts.each do |id, count|
            tr
              td= render id
              td= count