config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get :login, to: 'oauth#auth'
  get :logout, to: 'oauth#logout'

  namespace :oauth do
    get :callback
  end

  resources :tournaments do
    resources :players, only: [:index, :create, :update, :destroy] do
      get :standings, on: :collection
      get :meeting, on: :collection
      patch :drop, on: :member
      patch :reinstate, on: :member
    end
    resources :rounds, only: [:index, :show, :create, :edit, :update, :destroy] do
      resources :pairings, only: [:index, :create, :destroy] do
        post :report, on: :member
        get :match_slips, on: :collection
      end
      patch :repair, on: :member
      patch :complete, on: :member
    end
    resources :stages, only: [:create, :destroy]
    post :upload_to_abr, on: :member
    get :save_json, on: :member
    post :cut, on: :member
    get :qr, on: :member
    get :import_from_tome, on: :member
    post :apply_import_from_tome, on: :member
    get :import_from_csv, on: :member
    post :apply_import_from_csv, on: :member
    get :shortlink, on: :collection
    get :not_found, on: :collection
    get :my, on: :collection
  end
  resources :identities, only: [:index]

  get '/error', to: 'errors#show'

  get '/help', to: 'home#help'

  get ':slug', to: 'tournaments#shortlink'

  match '*path', to: redirect('/error'), via: :all
end

app/models/player.rb
class Player < ApplicationRecord
  include Pairable

  belongs_to :tournament
  belongs_to :previous, class_name: 'Player', optional: true
  has_one :next, class_name: 'Player', foreign_key: :previous_id
  has_many :registrations, dependent: :destroy

  before_destroy :destroy_pairings

  scope :active, -> { where(active: true) }
  scope :dropped, -> { where(active: false) }
  scope :with_first_round_bye, -> { where(first_round_bye: true) }

  def pairings
    Pairing.for_player(self)
  end

  def non_bye_pairings
    pairings.non_bye
  end

  def opponents
    pairings.map { |p| p.opponent_for(self) }
  end

  def non_bye_opponents
    non_bye_pairings.map { |p| p.opponent_for(self) }
  end

  def points
    @points ||= pairings.reported.sum { |pairing| pairing.score_for(self) }
  end

  def sos_earned
    @sos_earned ||= non_bye_pairings.reported.sum { |pairing| pairing.score_for(self) }
  end

  def drop!
    update(active: false)
  end

  def eligible_pairings
    pairings.completed
  end

  def seed_in_stage(stage)
    registrations.find_by(stage: stage).seed
  end

  def had_bye?
    pairings.bye.any?
  end

  def corp_identity_object
    Identity.find_or_initialize_by(name: corp_identity)
  end

  def runner_identity_object
    Identity.find_or_initialize_by(name: runner_identity)
  end

  private

  def destroy_pairings
    pairings.destroy_all
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_tournament
  before_action :set_player, only: [:update, :destroy, :drop, :reinstate]

  def index
    authorize @tournament, :update?

    @players = @tournament.players.active.sort_by { |p| p.name.downcase || '' }
    @dropped = @tournament.players.dropped.sort_by { |p| p.name.downcase || '' }
  end

  def create
    authorize @tournament, :update?

    player = @tournament.players.create(player_params)
    @tournament.current_stage.players << player

    redirect_to tournament_players_path(@tournament)
  end

  def update
    authorize @tournament, :update?

    @player.update(player_params)

    redirect_to tournament_players_path(@tournament)
  end

  def destroy
    authorize @tournament, :update?

    @player.destroy

    redirect_to tournament_players_path(@tournament)
  end

  def standings
    authorize @tournament, :show?
  end

  def drop
    authorize @tournament, :update?

    @player.update(active: false)

    redirect_to tournament_players_path(@tournament)
  end

  def reinstate
    authorize @tournament, :update?

    @player.update(active: true)

    redirect_to tournament_players_path(@tournament)
  end

  def meeting
    authorize @tournament, :show?
  end

  private

  def player_params
    params.require(:player)
      .permit(:name, :corp_identity, :runner_identity, :first_round_bye, :manual_seed)
  end

  def set_player
    @player = Player.find(params[:id])
  end
end

app/views/players/_player.html.slim
.tournament.col-12
  = player.name
  = " (Dropped)" unless player.active?

app/views/players/index.html.slim
.col-12.players
  p
    = link_to meeting_tournament_players_path(@tournament), class: 'btn btn-primary' do
      => fa_icon 'list'
      | Player meeting

  h3.mt-4 Register player
  = simple_form_for :player, url: tournament_players_path(@tournament), html: { class: 'form-inline identities_form' } do |f|
    => f.text_field :name, placeholder: 'Name', class: 'form-control mr-2'
    => f.text_field :corp_identity, placeholder: 'Corporation', class: 'corp_identities form-control mr-2'
    => f.text_field :runner_identity, placeholder: 'Runner', class: 'runner_identities form-control mr-2'
    .form-check.mr-2
      => f.input_field :first_round_bye, as: :boolean, inline_label: 'First round bye?', class: 'form-check-input'
    - if @tournament.manual_seed
      => f.text_field :manual_seed, placeholder: 'Seed', class: 'manual_seed form-control mr-2'
    = button_tag type: :submit, class: 'btn btn-success' do
      => fa_icon 'plus'
      | Create

  h3.mt-4 Players
  - @players.each do |player|
    = simple_form_for player, url: tournament_player_path(@tournament, player), html: { class: 'form-inline mb-2 identities_form' } do |f|
      => f.text_field :name, class: 'form-control mr-2'
      => f.text_field :corp_identity, placeholder: 'Corporation', class: 'corp_identities form-control mr-2'
      => f.text_field :runner_identity, placeholder: 'Runner', class: 'runner_identities form-control mr-2'
      .form-check.mr-2
        => f.input_field :first_round_bye, as: :boolean, inline_label: 'First round bye?', class: 'form-check-input'
      - if @tournament.manual_seed
        => f.text_field :manual_seed, placeholder: 'Seed', class: 'manual_seed form-control mr-2'
      = button_tag type: :submit, class: 'btn btn-primary mr-2' do
        => fa_icon 'floppy-o'
        | Save
      =< link_to drop_tournament_player_path(@tournament, player), method: :patch, class: 'btn btn-warning mr-2' do
        => fa_icon 'arrow-down'
        | Drop
      =< link_to tournament_player_path(@tournament, player), method: :delete, class: 'btn btn-danger mr-2' do
        => fa_icon 'trash'
        | Delete

  - if @dropped.any?
    h3.mt-4 Dropped
    - @dropped.each do |player|
      p
        | #{player.name} (#{player.corp_identity}, #{player.runner_identity})
        =< link_to reinstate_tournament_player_path(@tournament, player), method: :patch, class: 'btn btn-warning' do
          => fa_icon 'arrow-up'
          | Reinstate

app/views/players/meeting.html.slim
.col-12
  p.dontprint= link_to tournament_rounds_path(@tournament), class: 'btn btn-primary' do
    => fa_icon 'arrow-left'
    | Back to pairings

  h3 Player meeting

  table.table
    thead
      tr
        th #
        th Player 1
        th Player 2
    tbody
      - @tournament.players.map(&:name).sort_by{ |n| n.downcase }.in_groups_of(2).each_with_index do |pairing, i|
        tr
          td= i+1
          td= pairing[0]
          td= pairing[1]

app/views/players/standings.html.slim
.col-12
  h2 Standings
  - @tournament.stages.reverse.each do |stage|
    = render "players/standings/#{stage.format}", standings: stage.standings, stage: stage