config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get :login, to: 'oauth#auth'
  get :logout, to: 'oauth#logout'

  namespace :oauth do
    get :callback
  end

  resources :tournaments do
    resources :players, only: [:index, :create, :update, :destroy] do
      get :standings, on: :collection
      get :meeting, on: :collection
      patch :drop, on: :member
      patch :reinstate, on: :member
    end
    resources :rounds, only: [:index, :show, :create, :edit, :update, :destroy] do
      resources :pairings, only: [:index, :create, :destroy] do
        post :report, on: :member
        get :match_slips, on: :collection
      end
      patch :repair, on: :member
      patch :complete, on: :member
    end
    resources :stages, only: [:create, :destroy]
    post :upload_to_abr, on: :member
    get :save_json, on: :member
    post :cut, on: :member
    get :qr, on: :member
    get :import_from_tome, on: :member
    post :apply_import_from_tome, on: :member
    get :import_from_csv, on: :member
    post :apply_import_from_csv, on: :member
    get :shortlink, on: :collection
    get :not_found, on: :collection
    get :my, on: :collection
  end
  resources :identities, only: [:index]

  get '/error', to: 'errors#show'

  get '/help', to: 'home#help'

  get ':slug', to: 'tournaments#shortlink'

  match '*path', to: redirect('/error'), via: :all
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Cobra
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'

  body
    nav.navbar.navbar-expand-lg.fixed-top.navbar-dark.dontprint
      .container
        = link_to "Cobra", root_path, class: 'navbar-brand'
        button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
          span.navbar-toggler-icon
        #navbarNav.collapse.navbar-collapse
          ul.navbar-nav.ml-auto
            - if user_signed_in?
              li.nav-item= link_to new_tournament_path, class: 'nav-link' do
                => fa_icon 'plus'
                | Create tournament
              li.nav-item= link_to my_tournaments_path, class: 'nav-link' do
                => fa_icon 'trophy'
                | My tournaments
              li.nav-item= link_to logout_path, class: 'nav-link' do
                => fa_icon 'sign-out'
                | Sign out
            - else
              li.nav-item= link_to login_path, class: 'nav-link' do
                => fa_icon 'sign-in'
                | Sign in as TO
            li.nav-item= link_to help_path, class: 'nav-link' do
              => fa_icon 'life-ring'
              | How to
    .container
      - if @tournament
        .row.dontprint
          .col-10
            h1= @tournament.name
          .col-2.text-right
            - if @tournament.stream_url.present?
              = link_to @tournament.stream_url, class: 'stream-link', target: '_blank' do
                => fa_icon 'video-camera'
        ul.nav.nav-tabs.dontprint
          - if policy(@tournament).show?
            li.nav-item= link_to tournament_path(@tournament), class: "nav-link #{'active' if controller_name == 'tournaments' && action_name == 'show'}" do
              => fa_icon 'trophy'
              | Tournament
          - if policy(@tournament).edit?
            li.nav-item= link_to tournament_players_path(@tournament), class: "nav-link #{'active' if controller_name == 'players' && action_name == 'index'}" do
              => fa_icon 'users'
              | Players
          - if policy(@tournament).show?
            li.nav-item= link_to tournament_rounds_path(@tournament), class: "nav-link #{'active' if controller_name == 'rounds' || controller_name == 'pairings'}" do
              => fa_icon 'calendar-check-o'
              | Pairings
          - if policy(@tournament).show?
            li.nav-item= link_to standings_tournament_players_path(@tournament), class: "nav-link #{'active' if controller_name == 'players' && action_name == 'standings'}" do
              => fa_icon 'list-ol'
              | Standings
          - if policy(@tournament).edit?
            li.nav-item= link_to edit_tournament_path(@tournament), class: "nav-link #{'active' if controller_name == 'tournaments' && action_name != 'show'}" do
              => fa_icon 'cog'
              | Settings
      - if alert
        .row.py-3
          .col-12
            .alert.alert-danger= alert
      .row.py-3.main-content
        = yield
    .footer.dontprint
      .container
        .row
          .col-4.nav-item
            => link_to 'Donate on Patreon', 'https://www.patreon.com/neoreadinggrid'
            ' -
            = link_to 'Donate on PayPal', 'https://paypal.me/tojohno'
          .col-4.nav-item.text-center
           | Made with 🐍 by Johno
          .col-4.nav-item.text-right
            = link_to "v#{Rails.configuration.version}", 'https://github.com/muyjohno/cobra/releases', class: 'text-muted'